/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ToolsPanels;

import FileFactory.readingXml;
import FileFactory.savingXML;
import Tools.Selector;
import Shapes.Square;
import Shapes.Circle;
import Shapes.RightTriangle;
import Shapes.Line;
import Shapes.FreeHand;
import Shapes.Ellipse;
import Tools.Eraser;
import Shapes.Rectangle;
import Shapes.IsocelesTriangle;
import Tools.Mover;
import Tools.Resizer;
import Shapes.Shapes;
import WhateverPaint.MainWindow;
import java.util.Hashtable;
import javax.swing.JButton;
import javax.swing.JLabel;





public class ToolBoxs extends javax.swing.JPanel {

    public ToolBoxs() {
        initComponents();
        Hashtable<Integer, JLabel> labels = new Hashtable();
        labels.put(0, new JLabel("0"));
        labels.put(10, new JLabel("10"));
        labels.put(20, new JLabel("20"));

        MainWindow.old = freeHand;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rect = new javax.swing.JButton();
        ellipse = new javax.swing.JButton();
        circle = new javax.swing.JButton();
        freeHand = new javax.swing.JButton();
        line = new javax.swing.JButton();
        isoTrig = new javax.swing.JButton();
        rightTrig = new javax.swing.JButton();
        sqButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(83, 83, 83));
        setForeground(new java.awt.Color(83, 83, 83));
        setMaximumSize(new java.awt.Dimension(300, 300));
        setMinimumSize(new java.awt.Dimension(0, 0));
        setOpaque(false);

        rect.setBackground(new java.awt.Color(83, 83, 83));
        rect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/rect2.png"))); // NOI18N
        rect.setToolTipText("Rectangle");
        rect.setContentAreaFilled(false);
        rect.setOpaque(false);
        rect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rightTrigMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rightTrigMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rightTrigMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rightTrigMouseReleased(evt);
            }
        });
        rect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rectActionPerformed(evt);
            }
        });

        ellipse.setBackground(new java.awt.Color(83, 83, 83));
        ellipse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/elii.png"))); // NOI18N
        ellipse.setToolTipText("Ellipse");
        ellipse.setContentAreaFilled(false);
        ellipse.setOpaque(false);
        ellipse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rightTrigMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rightTrigMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rightTrigMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rightTrigMouseReleased(evt);
            }
        });
        ellipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ellipseActionPerformed(evt);
            }
        });

        circle.setBackground(new java.awt.Color(83, 83, 83));
        circle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/circular.png"))); // NOI18N
        circle.setToolTipText("Circle");
        circle.setContentAreaFilled(false);
        circle.setOpaque(false);
        circle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rightTrigMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rightTrigMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rightTrigMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rightTrigMouseReleased(evt);
            }
        });
        circle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                circleActionPerformed(evt);
            }
        });

        freeHand.setBackground(new java.awt.Color(83, 83, 83));
        freeHand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/pencil43.png"))); // NOI18N
        freeHand.setToolTipText("Free Hand");
        freeHand.setContentAreaFilled(false);
        freeHand.setOpaque(false);
        freeHand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rightTrigMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rightTrigMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rightTrigMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rightTrigMouseReleased(evt);
            }
        });
        freeHand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freeHandActionPerformed(evt);
            }
        });

        line.setBackground(new java.awt.Color(83, 83, 83));
        line.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/pencil154.png"))); // NOI18N
        line.setToolTipText("Line");
        line.setContentAreaFilled(false);
        line.setOpaque(false);
        line.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rightTrigMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rightTrigMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rightTrigMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rightTrigMouseReleased(evt);
            }
        });
        line.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineActionPerformed(evt);
            }
        });

        isoTrig.setBackground(new java.awt.Color(83, 83, 83));
        isoTrig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/iso22.png"))); // NOI18N
        isoTrig.setToolTipText("Triangle");
        isoTrig.setContentAreaFilled(false);
        isoTrig.setOpaque(false);
        isoTrig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rightTrigMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rightTrigMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rightTrigMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rightTrigMouseReleased(evt);
            }
        });
        isoTrig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isoTrigActionPerformed(evt);
            }
        });

        rightTrig.setBackground(new java.awt.Color(83, 83, 83));
        rightTrig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/rightTrig.png"))); // NOI18N
        rightTrig.setToolTipText("Right Triangle");
        rightTrig.setContentAreaFilled(false);
        rightTrig.setOpaque(false);
        rightTrig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rightTrigMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rightTrigMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rightTrigMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rightTrigMouseReleased(evt);
            }
        });
        rightTrig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightTrigActionPerformed(evt);
            }
        });

        sqButton.setBackground(new java.awt.Color(83, 83, 83));
        sqButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/squ.png"))); // NOI18N
        sqButton.setToolTipText("Square");
        sqButton.setContentAreaFilled(false);
        sqButton.setOpaque(false);
        sqButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rightTrigMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rightTrigMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rightTrigMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rightTrigMouseReleased(evt);
            }
        });
        sqButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rect, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ellipse, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sqButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(circle, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rightTrig, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(line, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(isoTrig, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(freeHand, javax.swing.GroupLayout.PREFERRED_SIZE, 48, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sqButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ellipse, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(line, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rightTrig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(circle, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(isoTrig, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(freeHand))))
                .addGap(4, 4, 4))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rectActionPerformed
        Canvas.setShape(new Rectangle());
        MainWindow.old = rect;
    }//GEN-LAST:event_rectActionPerformed

    private void ellipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ellipseActionPerformed
        Canvas.setShape(new Ellipse());
        MainWindow.old = ellipse;
    }//GEN-LAST:event_ellipseActionPerformed

    private void circleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_circleActionPerformed
        Canvas.setShape(new Circle());
        MainWindow.old = circle;
    }//GEN-LAST:event_circleActionPerformed

    private void freeHandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freeHandActionPerformed
        Canvas.setShape(new FreeHand());
        MainWindow.old = freeHand;
    }//GEN-LAST:event_freeHandActionPerformed

    private void lineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineActionPerformed
        Canvas.setShape(new Line());
        MainWindow.old = line;
    }//GEN-LAST:event_lineActionPerformed

    private void isoTrigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isoTrigActionPerformed
        Canvas.setShape(new IsocelesTriangle());
        MainWindow.old = isoTrig;
    }//GEN-LAST:event_isoTrigActionPerformed

    private void rightTrigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightTrigActionPerformed
        Canvas.setShape(new RightTriangle());
        MainWindow.old = rightTrig;
    }//GEN-LAST:event_rightTrigActionPerformed

    private void sqButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqButtonActionPerformed
        Canvas.setShape(new Square());

        MainWindow.old = sqButton;
    }//GEN-LAST:event_sqButtonActionPerformed

    private void rightTrigMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightTrigMouseExited
        JButton Button = (JButton) evt.getSource();
        CustomButtonStyle s = new CustomButtonStyle(Button);
        s.exit(Button);
    }//GEN-LAST:event_rightTrigMouseExited

    private void rightTrigMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightTrigMousePressed
        JButton Button = (JButton) evt.getSource();
        CustomButtonStyle s = new CustomButtonStyle(Button);
        s.press(Button);
    }//GEN-LAST:event_rightTrigMousePressed

    private void rightTrigMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightTrigMouseReleased
        JButton Button = (JButton) evt.getSource();
        CustomButtonStyle s = new CustomButtonStyle(Button);
        s.exit(Button);
    }//GEN-LAST:event_rightTrigMouseReleased

    private void rightTrigMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightTrigMouseEntered
        JButton Button = (JButton) evt.getSource();
        CustomButtonStyle s = new CustomButtonStyle(Button);
        s.release(Button);
    }//GEN-LAST:event_rightTrigMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton circle;
    private javax.swing.JButton ellipse;
    private javax.swing.JButton freeHand;
    private javax.swing.JButton isoTrig;
    private javax.swing.JButton line;
    private javax.swing.JButton rect;
    private javax.swing.JButton rightTrig;
    private javax.swing.JButton sqButton;
    // End of variables declaration//GEN-END:variables
}
